version: "3.9"

services:
  ip_domain_intel:
    build:
      context: ./IP_Domain_Intelligence
      dockerfile: dockerfile
    container_name: ip_domain_intel
    ports:
      - "9002:9002"
    env_file:
      - ./IP_Domain_Intelligence/.env  
    working_dir: /IP_Domain_Intelligence
    volumes:
      - ./IP_Domain_Intelligence:/IP_Domain_Intelligence

  natsflow:
    build:
      context: ./NatsFlow
      dockerfile: dockerfile
    container_name: NatsFlow
    ports:
      - "9003:9003"
    env_file:
      - ./NatsFlow/.env  
    working_dir: /NatsFlow
    volumes:
      - ./NatsFlow:/NatsFlow

  runmodel:
    build:
      context: ./RunModel
      dockerfile: dockerfile
    container_name: runmodel
    ports:
      - "9004:9004"
    env_file:
      - ./RunModel/.env
    working_dir: /RunModel
    volumes:
      - ./RunModel:/RunModel